name: Release Trigger

on:
  push:
    tags:
      - 'v*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo B workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACTION_RUN_TOKEN }}   # PAT stored in Repo A secrets
          repository: ankit-francis/Deployment_Repo
          event-type: update-dev-tag
          client-payload: >-
                          {"tag": "${{ github.event.release.tag_name || github.ref_name }}"}